# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.

require(File.join(File.dirname(__FILE__), 'config', 'boot'))

require 'rake'
require 'rake/testtask'
require 'rake/rdoctask'

require 'tasks/rails'

Rake::Task[:default].prerequisites.clear
Rake::Task[:default].actions.clear
task :default do
  50.times do
    print [".", 'E', 'F'][rand(3)]
    STDOUT.flush
    sleep 0.25
  end
  puts
  puts "Too many failures!"
end

task :new_features_test do
  20.times do
    print "."
    STDOUT.flush
    sleep 0.25
  end
  puts
  puts "All Tests Passed"
end
