development:
  adapter: sqlite3
  database: db/dev.sqlite3

test:
  adapter: sqlite3
  database: db/test.sqlite3
  min_messages: error

# Use the development database, but in production for benchmarking
production:
  adapter: sqlite3
  database: db/prod.squlite3
